### ISSUE TITLE
Scaling issues on MacOS Retina

### ISSUE THREAD

**Issue by sagacity** [RustAudio/baseview#105]
I'm seeing issues with the rendering of a VST UI in Reaper on a Macbook with a Retina display.

This happens both with `imgui-baseview` and with `egui-baseview`.

Here's what happens with the Gain example from `https://github.com/DGriffin91/imgui_baseview_test_vst2`, for instance (this is Reaper's "FX Chain" UI btw):

![Scaling issue](https://i.imgur.com/DUGt3tz.jpg)

The same thing happens with any other imgui or egui example. There _is_ some rendering going on though: changing the `clear_color` of the window has effect, for instance. The only way I can fix this is by hard-coding the `scale_factor` of the window to 1.0 [here](https://github.com/RustAudio/baseview/blob/master/src/macos/view.rs#L297). Supplying a `WindowScalePolicy::ScaleFactor(1.0)` in the `WindowOpenOptions` should do the same thing, but does not seem to have any effect.

If I manually double the window size in the example code [here](https://github.com/DGriffin91/imgui_baseview_test_vst2/blob/main/src/lib.rs#L33), then I do see the outlines of some UI being rendered, completely off-center and clipped:

![Scaling issue 2](https://i.imgur.com/1IQy8Kq.jpg)

Stepping through the `baseview` code, I do see that the logical size is the size that is being configured by me and the physical size is double that (since `scale_factor` is calculated to be 2.0). I am assuming the issue is not related specifically to either the imgui or egui renderers since they both exhibit the same behaviour. Additionally, running the `imgui-baseview` [examples](https://github.com/BillyDM/imgui-baseview/tree/main/examples) by themselves (i.e. outside of the VST host) works fine as well. So I'm a bit stumped on what the root cause could be.

**Comment by greatest-ape** [comment]
It might be related to the issue this PR solves: https://github.com/glowcoil/raw-gl-context/pull/13

**Comment by sagacity** [comment]
If I have some time soon, I'll try to give it a quick test!

**Comment by sagacity** [comment]
@greatest-ape I can confirm this solves the issue, when using the latest baseview and imgui-baseview revisions together with your raw-gl-context patch. Great :)

**Comment by greatest-ape** [comment]
@sagacity my PR has been merged now!

**Comment by sagacity** [comment]
Awesome 😍
